[theme]
base = "dark"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B27"
textColor = "#E7EAF1"
primaryColor = "#3E8EDE"
font = "sans serif"

[server]
headless = true
enableStaticServing = true
